version: 1
distro: fedora

meta:
  initramfs:
    files:
      - /usr/lib/modules/*/initramfs.img
  homebrew:
    files:
      - /usr/share/homebrew.tar.zst
  kernel:
    packages:
      - kernel*
    files:
      - /usr/lib/modules/*
      - /usr/lib/ostree-boot/*
  gamescope:
    packages:
      - gamescope*
  mesa:
    packages:
      - mesa*
  firmware:
    packages:
      - linux-firmware*
    files:
      # Bazzite dirty writes to /lib/firmware for the Steam Deck
      - /usr/lib/firmware/*